version: "3.8"
services:
  config:
    network_mode: host
    build: 
      context: taskcloud-config/
      network: host
    ports:
      - "8888:8888"
  discovery:
    network_mode: host
    build:
      context: taskcloud-discovery/
      network: host
    ports:
      - "8761:8761"
  service:
    network_mode: host
    build:
      context: taskcloud-service/
      network: host
    ports:
      - "8080:8080"

